name: Spark Framework CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
    name: Java Version ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      
      - name: Install latest Maven manually
        run: |
          MAVEN_VERSION=3.9.6
          curl -fsSL https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz -o maven.tar.gz
          tar -xvzf maven.tar.gz
          sudo mv apache-maven-${MAVEN_VERSION} /opt/maven
          echo "export PATH=/opt/maven/bin:$PATH" >> $GITHUB_ENV
          mvn -version  # Überprüfung der Version      
      
      - name: Run tests
        run: ./mvnw test
