name: Spark Framework CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17', '21' ]
    name: Java Version ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      
      - name: Install latest Maven
        run: |
          sudo apt update
          sudo apt install -y maven
          echo "mvn -version"
          mvn -version
          echo "./mvnw -version"
          ./mvnw -version
          
      - name: Run tests
        run: ./mvnw test
